name: Get latest release
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print date
        run: echo "The time is $(date)." >> hello.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
