name: Pull-Requests preview
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  pre-publish:
    permissions:
      contents: read # for TimonVS/pr-labeler-action to read config file
      pull-requests: write # for TimonVS/pr-labeler-action to add labels in PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print sha
        id: deploy-gh
        run: |
          echo ${{ github.sha }}
          echo "::set-output name=image::image/image:sha::${{ github.sha }}"

      - name: Print event
        run: echo ${{ github.event }}

      - name: Add image name to PR
        uses: unsplash/comment-on-pr@v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Image deployed to: ${{ steps.deploy-gh.outputs.image }}"
