name: Pull-Requests preview
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  pre-publish:
    permissions:
      contents: read # for TimonVS/pr-labeler-action to read config file
      pull-requests: write # for TimonVS/pr-labeler-action to add labels in PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print short SHA

        id: deploy-gh
        run: |
          echo ${{ github.sha }}
          echo "image=image/image:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Print event
        run: echo ${{ github.event }}

      - name: Add image name to PR
        uses: peter-evans/create-or-update-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Image deployed to: ${{ steps.deploy-gh.outputs.image }}
