name: Pull-Requests preview
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  pre-publish:
    permissions:
      contents: read # for TimonVS/pr-labeler-action to read config file
      pull-requests: write # for TimonVS/pr-labeler-action to add labels in PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Calculate image version
        id: image-version
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build image
        run: echo "build image with version ${{ steps.image-version.outputs.short_sha }}"

      - name: Push image
        id: push-image
        run: |
          echo "push image with version ${{ steps.image-version.outputs.short_sha }}"
          echo "image_complete=registy/repo/image/image:${{steps.image-version.outputs.short_sha}}" >> $GITHUB_OUTPUT

      - name: Add image name to PR
        uses: peter-evans/create-or-update-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Image deployed to: ${{ steps.push-image.outputs.image_complete }}. Please test it before merging2.
