name: Pull-Requests preview
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  pre-publish:
    permissions:
      contents: read # for TimonVS/pr-labeler-action to read config file
      pull-requests: write # for TimonVS/pr-labeler-action to add labels in PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Calculate image version
        id: image-version
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Prepare image
        id: prepare-image
        run: |
          echo "prepare image with version ${{ steps.image-version.outputs.short_sha }}"
          echo "image_name_complete=\"registy/repo/image/image:\<sub-name\>-${{steps.image-version.outputs.short_sha}}\"" >> $GITHUB_OUTPUT

      - name: Building commnet PR
        id: building-comment
        uses: peter-evans/create-or-update-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Image prepared to be deployed on ${{ steps.prepare-image.outputs.image_name_complete }}.
            Please wait for the build to finish before merging.

      - name: Build image
        run: |
          echo "build image with version ${{ steps.image-version.outputs.short_sha }}"
          sleep 10s

      - name: Pushing comment PR
        id: pushing-comment
        uses: peter-evans/create-or-update-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          comment-id: ${{ steps.building-comment.outputs.comment-id }}
          body: |
            Image prepared to be deployed on ${{ steps.prepare-image.outputs.image_name_complete }}.
            Please wait for the push to finish before merging.
          reactions: rocket
          edit-mode: replace

      - name: Push image
        id: push-image
        run: |
          echo "push image with version ${{ steps.image-version.outputs.short_sha }}"
          sleep 10s

      - name: Finished comment PR
        uses: peter-evans/create-or-update-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          comment-id: ${{ steps.pushing-comment.outputs.comment-id }}
          body: |
            Image deployed to: ${{ steps.prepare-image.outputs.image_name_complete }}.
            Please test it before merging.
          reactions: rocket,hooray
          edit-mode: replace

