name: Pull-Requests preview
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  pre-publish:
    permissions:
      contents: read # for TimonVS/pr-labeler-action to read config file
      pull-requests: write # for TimonVS/pr-labeler-action to add labels in PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Calculate image version
        id: image-version
        run: |
          echo "image=image/image:$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Print
        run: echo "build image and deploy with version ${{ steps.image-version.outputs.image }}"

      - name: Add image name to PR
        uses: peter-evans/create-or-update-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Image deployed to: ${{ steps.deploy-gh.outputs.image }}
