on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  writefile:
    runs-on: ubuntu-latest
    steps:
    - name: Write file
      run: |
        echo "Hello World" > file.txt
    - name: Run autotag.sh
      run: ./autotag.sh
    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: file
        path: file.txt