name: Tag release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  writefile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update version in package.xml
      run: |
        # Remove distro name from tag
        version=${${{ github.ref }}#*-}
        # Update version into all files packages.xml
        find . -name "package.xml" -type f -exec \
          sed -i "s#<version>.*</version>#<version>${version}</version>#g" {} \;
    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        # get version from tag
        version=${${{ github.ref }}/refs\/tags\//}
        echo "1"
        git commit -m "Update version to ${version}"
        echo "2"
        git tag -d ${version}
        echo "3"
        git tag ${version}
        echo "4"
        git push origin --force --tags
        echo "5"
