name: Tag release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  writefile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update version in package.xml
      run: |
        # Remove distro name from tag
        version=${${{ github.ref }}#*-}
        # Update version into all files packages.xml
        find . -name "package.xml" -type f -exec \
          sed -i "s#<version>.*</version>#<version>${version}</version>#g" {} \;
    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        version=${{ github.ref }}
        git commit -m "Update version to ${version}"
        git tag -d ${version}
        git tag -m "Release ${version}" ${version}
        git push origin --force --tags
